# Generated by Django 5.2 on 2025-04-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='field',
            name='size',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='field',
            name='surface',
            field=models.CharField(max_length=20),
        ),
    ]
