# Generated by Django 5.2 on 2025-04-05 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_field_price_per_hour_alter_field_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='amenities',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='FieldImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='media')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_set', to='fields.field')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
