# Generated by Django 5.2 on 2025-04-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0003_alter_field_amenities_fieldimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='images',
        ),
        migrations.AddField(
            model_name='field',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='field_images', to='fields.fieldimages'),
        ),
    ]
