# Generated by Django 5.2 on 2025-04-05 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0004_remove_field_images_field_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='images',
        ),
        migrations.AlterField(
            model_name='fieldimages',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fields.field'),
        ),
    ]
